### ISSUE TITLE
Note that there is another feature hidden in the filter model which is a declarative navigation though the tree where you want to do something with the nodes navigated to. In this case run the filter test predicate and based on the result create a remove operation for the path of the tested value.

### ISSUE THREAD

**Issue by iox666999** [dhis2/json-tree#56]
Note that there is another feature hidden in the filter model which is a declarative navigation though the tree where you want to do something with the nodes navigated to. In this case run the filter test predicate and based on the result create a remove operation for the path of the tested value. 

So a generic version would look something like
```java
record PathWalker<T extends JsonValue>(
  Class<T> as,
  Predicate<T> visit,  
  Map<String,PathWalker<T>> itemsByPath) {}
```
The `visit` is still a predicate (not a consumer) because it's role is twofold. It consumes the value to perform its action and returns true only if in the navigation should continue with the items.
In case of the filter the `consumer` would internally have to do the test and add the remove operation but then return the inverted test result as there is no need to go deeper if the node is removed.

_Originally posted by @jbee in https://github.com/dhis2/json-tree/issues/55#issuecomment-1932836839_

**Comment by jbee** [comment]
@iox666999 This issue looks like some automation gone wrong. I am going to close it. If you had a comment or want to open a new issue please redo it.
